### ISSUE TITLE
Please add libsonic support for faster speeds

### ISSUE THREAD

**Issue by stormdragon2976** [Olga-Yakovleva/RHVoice#94] opened 2018-11-03 14:05 UTC
Libsonic is a way to make synths, or anything else, produce much faster rates. So the speech rate could be doubled, or even trippled, people would be able to read much more quickly.
https://github.com/waywardgeek/sonic

Also, thanks for this synthesizer, it is awesome.

**Comment by beqabeqa473** [comment] 2018-11-03 14:08
hi.

if you review it deeply, you will see that sonic is already used by rhvoice.

On 11/3/18, stormdragon2976 <notifications@github.com> wrote:
> Libsonic is a way to make synths, or anything else, produce much faster
> rates. So the speech rate could be doubled, or even trippled, people would
> be able to read much more quickly.
> https://github.com/waywardgeek/sonic
>
> Also, thanks for this synthesizer, it is awesome.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Olga-Yakovleva/RHVoice/issues/94


-- 
with best regards beqa

**Comment by stormdragon2976** [comment] 2018-11-03 14:48
I am using the speech-dispatcher module. At its fastest rate, it is not using libsonic. I went looking for a RHVoice.conf file, but I don't see one. I assume the voice max rate could be set there. Does the module have a config file I can get from somewhere?

Also, the speech-dispatcher module is not listing the available voices. This is returned when I do spd-say -o RHVoice -L
Failed to get voice list.

**Comment by beqabeqa473** [comment] 2018-11-03 14:57
if i remember correctly, min_sonic_rate is an option, where you can
set on which minimum rate sonic should take an effect.
it is in RHVoice.conf

On 11/3/18, stormdragon2976 <notifications@github.com> wrote:
> I am using the speech-dispatcher module. At its fastest rate, it is not
> using libsonic. I went looking for a RHVoice.conf file, but I don't see one.
> I assume the voice max rate could be set there. Does the module have a
> config file I can get from somewhere?
>
> Also, the speech-dispatcher module is not listing the available voices. This
> is returned when I do spd-say -o RHVoice -L
> Failed to get voice list.
>
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/Olga-Yakovleva/RHVoice/issues/94#issuecomment-435593456


-- 
with best regards beqa

**Comment by Olga-Yakovleva** [comment] 2018-11-03 15:35
Currently it uses the system-wide configuration file. The default path 
is /usr/local/etc/RHVoice/RHVoice.conf. Though the comments there are in 
Russian.

To always use sonic to speed up speech, add the following to this file:

min_sonic_rate=1

As for Speech Dispatcher, could you run sd_rhvoice directly and type 
"INIT", press enter, then type "LIST VOICES". What output do you get?

**Comment by stormdragon2976** [comment] 2018-11-03 15:46
When I run sd_rhvoice I get:
sd_rhvoice: command not found

**Comment by Olga-Yakovleva** [comment] 2018-11-04 05:02
If it has been built, by default the output module, sd_rhvoice, gets 
installed into /usr/local/bin.

By the way, I forgot to mention that the latest version of RHVoice 
already uses libsonic by default on all platforms, except for Android.

**Comment by stormdragon2976** [comment] 2018-11-04 11:34
The original package did not include the sd_voice. I have added it and will submit an issue for the package.

I ran the commands, and here is the output:

LIST VOICES
200-Alan en none
200-Aleksandr ru none
200-Aleksandr+Alan ru none
200-Anatol uk none
200-Anna ru none
200-Azamat ky none
200-Bdl en none
200-Clb en none
200-Elena ru none
200-Elena+Clb ru none
200-Irina ru none
200-Natalia uk none
200-Natia ka none
200-Nazgul ky none
200-Slt en none
200-Spomenka eo none
200-Talgat tt none
200 OK VOICE LIST SENT

So it appears to be working.  I still do not get the voices when trying to list them with speech-dispatcher though:
[storm@yggdrasil rhvoice-git] $ spd-say -o RHVoice -L
Failed to get voice list.

**Comment by Olga-Yakovleva** [comment] 2018-11-04 12:35
Is Speech Dispatcher configured to be able to find sd_rhvoice? It can be 
done either in the main configuration file of Speech Dispatcher or by 
creating a symlink to sd_rhvoice in the directory where Speech 
Dispatcher's own modules are installed.

**Comment by vantu5z** [comment] 2018-11-04 16:28
You can get the list of output modules:
$ spd-say -O
OUTPUT MODULES
rhvoice
dummy
generic
espeak

So use "rhvoice" instead of "RHVoice":
$ spd-say -o rhvoice -L

04.11.2018 14:34, stormdragon2976 пишет:

**Comment by vantu5z** [comment] 2018-11-04 16:33
@stormdragon2976 , you can get the list of output modules:
$ `spd-say -O`
```
OUTPUT MODULES
rhvoice
dummy
generic
espeak
```

So use `rhvoice` instead of `RHVoice`:
$ `spd-say -o rhvoice -L`
```
                   NAME                 LANGUAGE                  VARIANT
                     Alan                       en                     none
                Aleksandr                       ru                     none
           Aleksandr+Alan                       ru                     none
                   Anatol                       uk                     none
                     Anna                       ru                     none
                   Azamat                       ky                     none
                      Bdl                       en                     none
                      Clb                       en                     none
                    Elena                       ru                     none
                Elena+Clb                       ru                     none
                    Irina                       ru                     none
                  Natalia                       uk                     none
                    Natia                       ka                     none
                   Nazgul                       ky                     none
                      Slt                       en                     none
                 Spomenka                       eo                     none
                   Talgat                       tt                     none
```

**Comment by stormdragon2976** [comment] 2018-11-04 16:36
Even with rhvoice instead of RHVoice it is still saying:
Failed to get voice list.

**Comment by vantu5z** [comment] 2018-11-04 16:39
Please show `spd-say -O` output.

**Comment by vantu5z** [comment] 2018-11-04 16:42
@stormdragon2976 , how I can understand you use Arch based Linux, so about config file:
$ `pacman -Ql rhvoice-git | grep conf`
`rhvoice-git /etc/RHVoice/RHVoice.conf`

Do you try config Speech Dispatcher by `spd-conf`?

**Comment by stormdragon2976** [comment] 2018-11-04 18:39
I did run spd-conf, that's what got the voice to show up in the first place. Interestingly, it is still not showing up on my Raspberry Pi, and I'm not sure why, I followed the same steps.  Here is the output from the commands you requested:

[storm@yggdrasil ~] $ spd-say -O
OUTPUT MODULES
rhvoice
espeak-ng
flite
dummy
generic
espeak
cicero

[storm@yggdrasil ~] $ pacman -Ql rhvoice-git | grep conf
rhvoice-git /etc/RHVoice/RHVoice.conf

**Comment by the-kyle** [comment] 2018-11-04 20:52
I have rhvoice in the list of output modules in my speech-dispatcher, but I still get no list of voices. My DefaultLanguage was en-US. So I tried changing it to en and restarting speech-dispatcher, but I still get no list of voices. Does /etc/RHVoice/RHVoice.conf need to be linked in a different location? I can definitely see the module, and its voices work. I can even specify them on the spd-say command line, but
  spd-say -O rhvoice -L
responds with
"failed to get voice list"

**Comment by Olga-Yakovleva** [comment] 2018-11-05 06:08
Could you temporarily set Speech Dispatcher's logging level to 5, 
restart it and execute "spd-say -o rhvoice -L"? Then send me 
speech-dispatcher.log privately? I'd like to see how exactly my module 
replies to SD's commands.

**Comment by stormdragon2976** [comment] 2018-11-07 02:00
Sorry it took me a bit to get back to you, I had some things come up.

I have the log file. but I'm not sure how to get it to you without attaching it here, so I'll just make a pastebin for it. There shouldn't be anything private in there.

http://dpaste.com/0NMKTPK

**Comment by Olga-Yakovleva** [comment] 2018-11-07 06:33
Thank you. Now I understand what the problem is and how it can be fixed. 
My module is compatible with the last stable version of Speech 
Dispatcher, but not compatible with the development version yet. They 
introduced a change which requires third-party modules to behave 
differently depending on the version of Speech Dispatcher.

By the way, my email is yakovleva.o.v@gmail.com.

**Comment by Olga-Yakovleva** [comment] 2018-11-11 06:03
I've committed a change that should make RHVoice compatible with Speech 
Dispatcher 0.9.

**Comment by stormdragon2976** [comment] 2018-11-13 02:18
This does work much better. Thank you.

**Comment by alex19EP** [comment] 2020-06-16 16:35
issue is fixed

**Closed by alex19EP** 2020-06-16 16:35 UTC
