### ISSUE TITLE
The English data package does not work on sapi 5

### ISSUE THREAD

**Issue by fatihyuksek1** [Olga-Yakovleva/RHVoice#186] opened 2020-08-23 10:53 UTC
When I install the English language data pack with the anna and bdl voices (English and Russian voices), isn't it supposed to read the lating characters in English and the cyrillic characters in Russian? It doesn't work and nothing seems to differ whether I have installed the language data pack or not. I want it to read the latin letters with bdl and the cyrillic letters with anna on sapi 5.

**Comment by fatihyuksek1** [comment] 2020-08-24 08:25
There ‘s no rhvoice directory in the %appdata% directory  Windows 10 için Posta ile gönderildi Kimden: zstanecicGönderilme: 23 Ağustos 2020 Pazar 15:21Kime: Olga-Yakovleva/RHVoiceBilgi: fatihyuksek1; AuthorKonu: Re: [Olga-Yakovleva/RHVoice] The English data package does not work on sapi 5 (#186) Hi,See the configuration documentation in the wiki.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Olga-Yakovleva** [comment] 2020-08-31 15:40
For now the directory may just be created manually. The next version will create it and copy the file with the links to the configuration-related materials.

**Comment by Olga-Yakovleva** [comment] 2020-08-31 15:43
But the issue described is not a bug as such, as the voice profiles are meant to be configured by the user themself in whichever combination they prefer. So closing.

**Closed by Olga-Yakovleva** 2020-08-31 15:43 UTC
