### ISSUE TITLE
Questioning intonation (wish list item, not a bug)

### ISSUE THREAD

**Issue by gregko** [Olga-Yakovleva/RHVoice#116] opened 2019-08-24 23:52 UTC
I just found out that your RHVoice TTS engine and voices work very well with my @Voice Aloud Reader on Android. However, one thing I notice is something that the users of my app using Google TTS voices complain a lot: questions sound like statements. For example, a question "Нравится ли вам это?" all 4 Russian voices read like "Нравится ли вам это." It would be nice to hear the rising intonation for sentences ending with a question mark.

Other than that, it's really excellent work, congratulations on your achievement!

**Comment by zvezdochiot** [comment] 2019-09-23 09:48
More likely to you here: #97

**Comment by alex19EP** [comment] 2020-06-16 14:32
Duplicate of #97

**Closed by alex19EP** 2020-06-16 14:32 UTC
